In [2]:
import pandas as pd

# A DataFrame is essentially a table
data = {
    "product": ["Notebook", "Pen", "Backpack"],
    "price":   [8.99, 1.25, 39.00],
    "units":   [42, 130, 17],
}
df = pd.DataFrame(data)
print(df)

    product  price  units
0  Notebook   8.99     42
1       Pen   1.25    130
2  Backpack  39.00     17

In [3]:
from pathlib import Path

In [4]:
Path

pathlib._local.Path

In [5]:
df=pd.read_csv(Path("..") /"data"/"raw"/"paperlane_orders.csv")

In [6]:
df.head()

,order_id,order_date,customer,region,product,quantity,unit_price,status
0,1001,2026-01-05,Ava,East,Notebook,2,8.99,Complete
1,1002,2026-01-05,Miles,Midwest,Pen,10,1.25,complete
2,1003,2026-01-06,Noah,West,Notebook,1,8.99,Complete
3,1004,2026-01-06,Ava,East,Backpack,1,NaN,Returned
4,1005,2026-01-07,Priya,South,Pen,5,1.25,Complete

In [7]:
df.head(10)

,order_id,order_date,customer,region,product,quantity,unit_price,status
0,1001,2026-01-05,Ava,East,Notebook,2,8.99,Complete
1,1002,2026-01-05,Miles,Midwest,Pen,10,1.25,complete
2,1003,2026-01-06,Noah,West,Notebook,1,8.99,Complete
3,1004,2026-01-06,Ava,East,Backpack,1,NaN,Returned
4,1005,2026-01-07,Priya,South,Pen,5,1.25,Complete
5,1006,2026-01-07,Noah,West,Marker,3,2.50,COMPLETE
6,1007,2026-01-08,Miles,Midwest,Backpack,2,39.00,Complete
7,1007,2026-01-08,Miles,Midwest,Backpack,2,39.00,Complete
8,1008,2026-01-08,Ava,NaN,Marker,4,2.50,Complete
9,1009,01/09/2026,Priya,South,Notebook,2,8.99,Complete

In [8]:
df.tail()             #checking last rows

,order_id,order_date,customer,region,product,quantity,unit_price,status
5,1006,2026-01-07,Noah,West,Marker,3,2.50,COMPLETE
6,1007,2026-01-08,Miles,Midwest,Backpack,2,39.00,Complete
7,1007,2026-01-08,Miles,Midwest,Backpack,2,39.00,Complete
8,1008,2026-01-08,Ava,NaN,Marker,4,2.50,Complete
9,1009,01/09/2026,Priya,South,Notebook,2,8.99,Complete

In [9]:
df.shape  #row, columns

(10, 8)

In [10]:
print(type(df.columns))
df.columns.tolist()   #creating that index to a list

<class 'pandas.core.indexes.base.Index'>

['order_id',
 'order_date',
 'customer',
 'region',
 'product',
 'quantity',
 'unit_price',
 'status']

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   order_id    10 non-null     int64
 1   order_date  10 non-null     object
 2   customer    10 non-null     object
 3   region      9 non-null      object
 4   product     10 non-null     object
 5   quantity    10 non-null     int64
 6   unit_price  9 non-null      float64
 7   status      10 non-null     object
dtypes: float64(1), int64(2), object(5)
memory usage: 772.0+ bytes

In [12]:
df.describe()

         order_id   quantity  unit_price
count    10.00000  10.000000    9.000000
mean   1005.20000   3.200000   12.496667
std       2.65832   2.699794   15.389059
min    1001.00000   1.000000    1.250000
25%    1003.25000   2.000000    2.500000
50%    1005.50000   2.000000    8.990000
75%    1007.00000   3.750000    8.990000
max    1009.00000  10.000000   39.000000

In [13]:
df.describe(include='all')

,order_id,order_date,customer,region,product,quantity,unit_price,status
count,10.00000,10,10,9,10,10.000000,9.000000,10
unique,NaN,5,4,5,4,NaN,NaN,4
top,NaN,2026-01-08,Ava,Midwest,Notebook,NaN,NaN,Complete
freq,NaN,3,3,3,3,NaN,NaN,7
mean,1005.20000,NaN,NaN,NaN,NaN,3.200000,12.496667,NaN
std,2.65832,NaN,NaN,NaN,NaN,2.699794,15.389059,NaN
min,1001.00000,NaN,NaN,NaN,NaN,1.000000,1.250000,NaN
25%,1003.25000,NaN,NaN,NaN,NaN,2.000000,2.500000,NaN
50%,1005.50000,NaN,NaN,NaN,NaN,2.000000,8.990000,NaN
75%,1007.00000,NaN,NaN,NaN,NaN,3.750000,8.990000,NaN
max,1009.00000,NaN,NaN,NaN,NaN,10.000000,39.000000,NaN

In [14]:
df.isna()

,order_id,order_date,customer,region,product,quantity,unit_price,status
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,True,False
4,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False
8,False,False,False,True,False,False,False,False
9,False,False,False,False,False,False,False,False

In [15]:
df.isna().sum()

order_id      0
order_date    0
customer      0
region        1
product       0
quantity      0
unit_price    1
status        0
dtype: int64

In [16]:
df.duplicated().sum()

np.int64(1)

In [17]:
#access the region colum
df['region'].value_counts()

region
Midwest    3
East       2
South      2
 West      1
West       1
Name: count, dtype: int64

In [18]:
df['status'].value_counts()

status
Complete    7
complete    1
Returned    1
COMPLETE    1
Name: count, dtype: int64

In [19]:
df['region'].value_counts(normalize=True)

region
Midwest    0.333333
East       0.222222
South      0.222222
 West      0.111111
West       0.111111
Name: proportion, dtype: float64

handling missing values and duplicates

In [20]:
print("Before:", df.shape)
df = df.drop_duplicates()
print("After:", df.shape)

Before: (10, 8)
After: (9, 8)

In [21]:
#df.reset_index()

In [22]:
df

,order_id,order_date,customer,region,product,quantity,unit_price,status
0,1001,2026-01-05,Ava,East,Notebook,2,8.99,Complete
1,1002,2026-01-05,Miles,Midwest,Pen,10,1.25,complete
2,1003,2026-01-06,Noah,West,Notebook,1,8.99,Complete
3,1004,2026-01-06,Ava,East,Backpack,1,NaN,Returned
4,1005,2026-01-07,Priya,South,Pen,5,1.25,Complete
5,1006,2026-01-07,Noah,West,Marker,3,2.50,COMPLETE
6,1007,2026-01-08,Miles,Midwest,Backpack,2,39.00,Complete
8,1008,2026-01-08,Ava,NaN,Marker,4,2.50,Complete
9,1009,01/09/2026,Priya,South,Notebook,2,8.99,Complete

In [23]:
df = df.dropna(subset=["unit_price"])
df

,order_id,order_date,customer,region,product,quantity,unit_price,status
0,1001,2026-01-05,Ava,East,Notebook,2,8.99,Complete
1,1002,2026-01-05,Miles,Midwest,Pen,10,1.25,complete
2,1003,2026-01-06,Noah,West,Notebook,1,8.99,Complete
4,1005,2026-01-07,Priya,South,Pen,5,1.25,Complete
5,1006,2026-01-07,Noah,West,Marker,3,2.50,COMPLETE
6,1007,2026-01-08,Miles,Midwest,Backpack,2,39.00,Complete
8,1008,2026-01-08,Ava,NaN,Marker,4,2.50,Complete
9,1009,01/09/2026,Priya,South,Notebook,2,8.99,Complete

In [24]:
df["region"] = df["region"].fillna("Unknown")
df

C:\Users\Jbeat\AppData\Local\Temp\ipykernel_19112\2664159305.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["region"] = df["region"].fillna("Unknown")

,order_id,order_date,customer,region,product,quantity,unit_price,status
0,1001,2026-01-05,Ava,East,Notebook,2,8.99,Complete
1,1002,2026-01-05,Miles,Midwest,Pen,10,1.25,complete
2,1003,2026-01-06,Noah,West,Notebook,1,8.99,Complete
4,1005,2026-01-07,Priya,South,Pen,5,1.25,Complete
5,1006,2026-01-07,Noah,West,Marker,3,2.50,COMPLETE
6,1007,2026-01-08,Miles,Midwest,Backpack,2,39.00,Complete
8,1008,2026-01-08,Ava,Unknown,Marker,4,2.50,Complete
9,1009,01/09/2026,Priya,South,Notebook,2,8.99,Complete

In [25]:
# Strategy 1: Drop rows where a critical column is null
# df = df.dropna(subset=["unit_price"])

# Strategy 2: Fill with a fixed value
# df["region"] = df["region"].fillna("Unknown")

# Strategy 3: Fill numeric columns with the median
# df["unit_price"] = 
df["unit_price"].fillna(df["unit_price"].median())

0     8.99
1     1.25
2     8.99
4     1.25
5     2.50
6    39.00
8     2.50
9     8.99
Name: unit_price, dtype: float64

In [26]:
# Strip leading/trailing whitespace
df['region']=df["region"].str.strip()
df

C:\Users\Jbeat\AppData\Local\Temp\ipykernel_19112\1297518311.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['region']=df["region"].str.strip()

,order_id,order_date,customer,region,product,quantity,unit_price,status
0,1001,2026-01-05,Ava,East,Notebook,2,8.99,Complete
1,1002,2026-01-05,Miles,Midwest,Pen,10,1.25,complete
2,1003,2026-01-06,Noah,West,Notebook,1,8.99,Complete
4,1005,2026-01-07,Priya,South,Pen,5,1.25,Complete
5,1006,2026-01-07,Noah,West,Marker,3,2.50,COMPLETE
6,1007,2026-01-08,Miles,Midwest,Backpack,2,39.00,Complete
8,1008,2026-01-08,Ava,Unknown,Marker,4,2.50,Complete
9,1009,01/09/2026,Priya,South,Notebook,2,8.99,Complete

In [27]:
print(df["region"].value_counts())

region
Midwest    2
West       2
South      2
East       1
Unknown    1
Name: count, dtype: int64

In [28]:
print(df["status"].value_counts())

status
Complete    6
complete    1
COMPLETE    1
Name: count, dtype: int64

In [29]:
df["status"]=df["status"].str.strip().str.title()
print(df["status"].value_counts())

status
Complete    8
Name: count, dtype: int64

C:\Users\Jbeat\AppData\Local\Temp\ipykernel_19112\3865884498.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["status"]=df["status"].str.strip().str.title()

In [30]:
df

,order_id,order_date,customer,region,product,quantity,unit_price,status
0,1001,2026-01-05,Ava,East,Notebook,2,8.99,Complete
1,1002,2026-01-05,Miles,Midwest,Pen,10,1.25,Complete
2,1003,2026-01-06,Noah,West,Notebook,1,8.99,Complete
4,1005,2026-01-07,Priya,South,Pen,5,1.25,Complete
5,1006,2026-01-07,Noah,West,Marker,3,2.50,Complete
6,1007,2026-01-08,Miles,Midwest,Backpack,2,39.00,Complete
8,1008,2026-01-08,Ava,Unknown,Marker,4,2.50,Complete
9,1009,01/09/2026,Priya,South,Notebook,2,8.99,Complete

In [32]:

df

,order_id,order_date,customer,region,product,quantity,unit_price,status
0,1001,2026-01-05,Ava,East,Notebook,2,8.99,Complete
1,1002,2026-01-05,Miles,Midwest,Pen,10,1.25,Complete
2,1003,2026-01-06,Noah,West,Notebook,1,8.99,Complete
4,1005,2026-01-07,Priya,South,Pen,5,1.25,Complete
5,1006,2026-01-07,Noah,West,Marker,3,2.50,Complete
6,1007,2026-01-08,Miles,Midwest,Backpack,2,39.00,Complete
8,1008,2026-01-08,Ava,Unknown,Marker,4,2.50,Complete

In [33]:

f = df.head(7)

df['order_date'] = pd.to_datetime(df['order_date'])

df

df.info()

# create a new column, df['name_of_new_col'] = value

df['order_month'] = df['order_date'].dt.month

df

df['order_day_of_week'] = df['order_date'].dt.day_name()

df['revenue'] = df['quantity'] * df['unit_price']

df

<class 'pandas.core.frame.DataFrame'>
Index: 7 entries, 0 to 8
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   order_id    7 non-null      int64
 1   order_date  7 non-null      datetime64[ns]
 2   customer    7 non-null      object
 3   region      7 non-null      object
 4   product     7 non-null      object
 5   quantity    7 non-null      int64
 6   unit_price  7 non-null      float64
 7   status      7 non-null      object
dtypes: datetime64[ns](1), float64(1), int64(2), object(4)
memory usage: 504.0+ bytes

C:\Users\Jbeat\AppData\Local\Temp\ipykernel_19112\2000587532.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['order_date'] = pd.to_datetime(df['order_date'])
C:\Users\Jbeat\AppData\Local\Temp\ipykernel_19112\2000587532.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['order_month'] = df['order_date'].dt.month
C:\Users\Jbeat\AppData\Local\Temp\ipykernel_19112\2000587532.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['order_day_of_week'] = df['order_date'].dt.day_name()
C:\Users\Jbeat\AppData\Local\Temp\ipykernel_19112\2000587532.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['revenue'] = df['quantity'] * df['unit_price']

,order_id,order_date,customer,region,product,quantity,unit_price,status,order_month,order_day_of_week,revenue
0,1001,2026-01-05,Ava,East,Notebook,2,8.99,Complete,1,Monday,17.98
1,1002,2026-01-05,Miles,Midwest,Pen,10,1.25,Complete,1,Monday,12.50
2,1003,2026-01-06,Noah,West,Notebook,1,8.99,Complete,1,Tuesday,8.99
4,1005,2026-01-07,Priya,South,Pen,5,1.25,Complete,1,Wednesday,6.25
5,1006,2026-01-07,Noah,West,Marker,3,2.50,Complete,1,Wednesday,7.50
6,1007,2026-01-08,Miles,Midwest,Backpack,2,39.00,Complete,1,Thursday,78.00
8,1008,2026-01-08,Ava,Unknown,Marker,4,2.50,Complete,1,Thursday,10.00

In [35]:
df_complete = df[df["status"] == "Complete"].copy()
print(f"Complete orders: {len(df_complete)} of {len(df)} total")
df_complete

Complete orders: 7 of 7 total

,order_id,order_date,customer,region,product,quantity,unit_price,status,order_month,order_day_of_week,revenue
0,1001,2026-01-05,Ava,East,Notebook,2,8.99,Complete,1,Monday,17.98
1,1002,2026-01-05,Miles,Midwest,Pen,10,1.25,Complete,1,Monday,12.50
2,1003,2026-01-06,Noah,West,Notebook,1,8.99,Complete,1,Tuesday,8.99
4,1005,2026-01-07,Priya,South,Pen,5,1.25,Complete,1,Wednesday,6.25
5,1006,2026-01-07,Noah,West,Marker,3,2.50,Complete,1,Wednesday,7.50
6,1007,2026-01-08,Miles,Midwest,Backpack,2,39.00,Complete,1,Thursday,78.00
8,1008,2026-01-08,Ava,Unknown,Marker,4,2.50,Complete,1,Thursday,10.00

In [36]:
df_complete.to_csv(Path('..')/"data"/"processed"/"paperlane_orders_clean.csv", index=False)